<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Akash-Deb" failures="1" tests="4" name="vtiger.opportunity_module.ToCreateOpportunityTest" time="15.138" errors="0" timestamp="27 Apr 2024 11:48:08 GMT" skipped="3">
  <testcase classname="vtiger.opportunity_module.ToCreateOpportunityTest" name="createOpportunityAndVerifyOpportunity" time="3.090">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at vtiger.opportunity_module.ToCreateOpportunityTest.createOpportunityAndVerifyOpportunity(ToCreateOpportunityTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOpportunityAndVerifyOpportunity -->
  <testcase classname="vtiger.opportunity_module.ToCreateOpportunityTest" name="createOpportunityAndVerifyOpportunity" time="3.991">
    <skipped/>
  </testcase> <!-- createOpportunityAndVerifyOpportunity -->
  <testcase classname="vtiger.opportunity_module.ToCreateOpportunityTest" name="createOpportunityAndVerifyOpportunity" time="4.320">
    <skipped/>
  </testcase> <!-- createOpportunityAndVerifyOpportunity -->
  <testcase classname="vtiger.opportunity_module.ToCreateOpportunityTest" name="createOpportunityAndVerifyOpportunity" time="3.737">
    <skipped/>
  </testcase> <!-- createOpportunityAndVerifyOpportunity -->
</testsuite> <!-- vtiger.opportunity_module.ToCreateOpportunityTest -->
